name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - master  

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    - name: Set up Maven
      uses: actions/setup-maven@v2
      with:
        maven-version: '3.8.1'  # Use the version of Maven you require

    - name: Build the application with Maven
      run: mvn clean package -DskipTests

    - name: Set up OpenShift CLI
      uses: redhat-actions/oc-cli@v2

    - name: Log in to OpenShift
      env:
        OPENSHIFT_API_URL: ${{ secrets.OPENSHIFT_API_URL }}
        OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      run: |
        oc login $OPENSHIFT_API_URL --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify=true

    - name: Set project to agile-dev
      run: |
        oc project agile-dev

    - name: Build and deploy the app to OpenShift
      run: |
        # OpenShift setup uses Source-to-Image (S2I) 
        oc start-build health-tracker-with-db --from-dir=target/ --follow
    
    - name: Check deployment status
      run: |
        oc rollout status deployment/health-tracker-with-db
